### ISSUE TITLE
Sync stops completely if at least one table is misconfigured.

### ISSUE THREAD

**Issue by finguin** [Karlodun/salesforce2pg#1]
We tried to add some new tables. Somehow we configured one column which did not exist in one of the tables (only in others) in Salesforce. The whole sync process stopped.
It would be good if only misconfigured tables / instances would fail and everything else would go through.

**Comment by Karlodun** [comment]
Added a feature to handle SOQL API errors. Further error handling would be required, but I'm lacking the time and resources right now.
Probably next month.
